# Generated by Django 3.0.14 on 2022-11-22 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_familia', '0002_curso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='curso',
        ),
    ]
