# Generated by Django 3.0.14 on 2022-11-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_familia', '0003_delete_curso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='familia',
            new_name='Familiares',
        ),
    ]
